spring.datasource.url=jdbc:postgresql://dpg-d7o4ekbbc2fs7396darg-a:5432/beer_management_db
spring.datasource.username=beer_management_db_user
spring.datasource.password=HN21tcswIFup6wb1wRAwFgvxEyjMqdQY

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh